version: '3.7'
services:

  backend:
    build: .
    depends_on:
      - redis
    ports:
      - "8080:8080"
    environment:
      - SERVER_PORT=8080
      - SPRING_REDIS_HOST=redis
      - SPRING_PORT=6379
      - SPRING_REDIS_TIMEOUT=30000

    networks:
      - network_local


  redis:
    image: redis
    networks:
      - network_local

networks:
  network_local: